### PR TITLE
Fixed improper deferred API usage

### PR DESCRIPTION
**Pull request by andyperlitch**
deferred.promise.complete is not actually a function. The correct way to resolve a promise is to call fulfill on its deferred

### CODE REVIEW

**Comment by andyperlitch** [comment]
I am curious how [these tests](https://github.com/kbaltrinic/http-backend-proxy/blob/master/test/unit/buffering-spec.js#L175-L182) were passing

**Comment by kbaltrinic** [comment]
Andy.  Apologies for the somewhat confusing code.  Keep in mind that these are unit tests.  These is no real protractor instance in play but a [fake](https://github.com/kbaltrinic/http-backend-proxy/blob/master/test/unit/helpers/protractor-browser.js) that supports its own api-of-convenience.  Your change actually breaks the tests.  

Your effort has pointed out though that my Travis configuration is also broken because your change passed all checks when it should not have.  There's a [typo in the yaml](https://github.com/kbaltrinic/http-backend-proxy/blob/v1.4.2/.travis.yml#L13) that I need to fix.  Thank you for helping to find that.

**Comment by andyperlitch** [comment]
You're very welcome, however why is my fix invalid? `complete` is not a function on a protractor promise...

**Comment by kbaltrinic** [comment]
Further apologies for such a muddle-headed response.  The fake does indeed explain why the tests were passing but obviously a fake with an API that doesn't match the real object, doesn't much sense does it.  I am wondering if this is a case of the API having changed over time I wrote against a now-out-of-date API?  

It seems that a test needs to be added to [e2e buffering spec](https://github.com/kbaltrinic/http-backend-proxy/blob/master/test/e2e/buffering-spec.js) to assert that calling flush on an empty buffer does not blow up.  Want to take a crack at that as a proof case for the necessity of your change?

**Comment by kbaltrinic** [comment]
That there might be a bug was bothering me so I wrote the e2e test to expose the issue and made the other necessary changes, and have released this as v 1.4.3. Thanks again for finding this!

**Pull request merged**
